# Generated by Django 5.2.13 on 2026-04-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_seller_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
